version: "3.8"

services:

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            - kafka-host
    
    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        expose:
            - "9091"
        networks:
            - kafka-host
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9091,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9091,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic_1:2:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    postgres:
        container_name: postgres
        build:
            context: .
            dockerfile: ./postgres/Dockerfile
        environment:
            POSTGRES_PASSWORD: postgrespass
            POSTGRES_DB: kafka_messages
        ports:
            - "5432:5432"
        networks:
            - kafka-host
            
networks:
    kafka-host:
        name: kafka-host